// Auto-generated by scripts/build-wasm.js — do not edit manually
// Rebuild with: pnpm wasm:build
// Source: assembly/index.ts → build/ai.wasm (1.2 KB, 1257 bytes)

export const AI_WASM_BASE64 =
  'AGFzbQEAAAABHAVgAn9/AX9gA39/fwF/YAR/f39/AGABfwBgAAACDQEDZW52BWFib3J0AAIDCgkAAQEAAAABAwQFAwEAAQYNAn8BQbngAAt/AUEACwd2CA5nZXRSb3VuZFdpbm5lcgABCmlzR2FtZU92ZXIAAhNkZXRlcm1pbmVHYW1lV2lubmVyAAMPY2FsY3VsYXRlU2NvcmVzAAQJaGFzaE1vdmVzAAUNc2VsZWN0Q1BVTW92ZQAHB3NldFNlZWQACAZtZW1vcnkCAAgBCQwBCgqhBglAAQF/AkAgACABRg0AQQEhAkEBIAFFIABBAUZxIABFIAFBAkZxBH9BAQUgAUEBRiAAQQJGcQsbDQBBAiECCyACCxUAIAJBAm1BAWoiAiABTCAAIAJOcgspACACQQJtQQFqIgIgAUwgACACTnJFBEBBAA8LIAAgAUoEQEEBDwtBAgtPAQR/A0AgASACSgRAIAAgAkECdGooAgAiBUEBRgRAIARBAWohBAUgA0EBaiADIAVBAkYbIQMLIAJBAWohAgwBCwsgA0H//wNxIARBEHRyCzUBAn9BhSohAgNAIAEgA0oEQCAAIANBAnRqKAIAIAJBBXQgAmpzIQIgA0EBaiEDDAELCyACC8YBAQZ/IABB7P///wNLBEBBwAhBgAlB1gBBHhAAAAsgAEEQaiIEQfz///8DSwRAQcAIQYAJQSFBHRAAAAsjASMBQQRqIgIgBEETakFwcUEEayIEaiIFPwAiBkEQdEEPakFwcSIHSwRAIAYgBSAHa0H//wNqQYCAfHFBEHYiByAGIAdKG0AAQQBIBEAgB0AAQQBIBEAACwsLIAUkASAENgIAIAJBBGsiA0EANgIEIANBADYCCCADIAE2AgwgAyAANgIQIAJBEGoLwAIBAX8gAiQAIAFBAk4EQCAAIAFBAWtBA2wiAkECdGooAgAhASAAIAJBAWpBAnRqKAIAIQMgACACQQJqQQJ0aigCAEECRgR/IwBB7ZyZjgRsQbngAGpB/////wdxJAAjALhEAADA////30GjRGZmZmZmZuY/YwVBAAsEQCADDwtBDEEBEAYiAEGgCEEM/AoAAEEQQQQQBiICIAA2AgAgAiAANgIEIAJBDDYCCCACQQM2AgwgASACKAIMTwRAQcAJQYAKQfIAQSoQAAALIAIoAgQgAUECdGooAgAhACMAQe2cmY4EbEG54ABqQf////8HcSQAIwC4RAAAwP///99Bo0QzMzMzMzPjP2MEQCAADwsLIwBB7ZyZjgRsQbngAGpB/////wdxJAAjALhEAADA////30GjRAAAAAAAAAhAovwCCwYAIAAkAAsHAEGcCiQBCwvvAQoAQYwICwEcAEGYCAsNAQAAAAwAAAABAAAAAgBBrAgLATwAQbgICy8CAAAAKAAAAEEAbABsAG8AYwBhAHQAaQBvAG4AIAB0AG8AbwAgAGwAYQByAGcAZQBB7AgLATwAQfgICyUCAAAAHgAAAH4AbABpAGIALwByAHQALwBzAHQAdQBiAC4AdABzAEGsCQsBPABBuAkLKwIAAAAkAAAASQBuAGQAZQB4ACAAbwB1AHQAIABvAGYAIAByAGEAbgBnAGUAQewJCwEsAEH4CQshAgAAABoAAAB+AGwAaQBiAC8AYQByAHIAYQB5AC4AdABz'

let wasmInstance: WebAssembly.Instance | null = null
let wasmMemory: WebAssembly.Memory | null = null
let dataBuffer: Int32Array | null = null

/**
 * Initialize WASM module if available.
 * This strategy falls back to JS if WASM fails.
 */
export async function initWasm(): Promise<boolean> {
  if (!AI_WASM_BASE64) {
    return false
  }

  try {
    const binaryString = atob(AI_WASM_BASE64)
    const bytes = new Uint8Array(binaryString.length)
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i)
    }

    const wasmModule = await WebAssembly.instantiate(bytes, {
      env: {
        __memory_base: 0,
      },
    })

    wasmInstance = wasmModule.instance
    wasmMemory = wasmModule.instance.exports.memory as WebAssembly.Memory
    dataBuffer = new Int32Array(wasmMemory.buffer)

    return true
  } catch (err) {
    console.warn('WASM initialization failed, falling back to JS:', err)
    return false
  }
}

/**
 * Select CPU move using WASM if available, otherwise fall back to JS.
 * Encodes rounds as flat Int32Array for WASM processing.
 */
export function selectCPUMoveWasm(
  rounds: Array<{ playerMove: string; cpuMove: string; result: string }>,
  seed: number,
): number | null {
  if (!wasmInstance || !dataBuffer) {
    return null
  }

  try {
    const memory = dataBuffer
    const basePtr = 0

    // Encode rounds into memory
    const moveMap: Record<string, number> = { rock: 0, paper: 1, scissors: 2 }
    const resultMap: Record<string, number> = { draw: 0, win: 1, loss: 2 }

    for (let i = 0; i < rounds.length; i++) {
      const round = rounds[i]
      memory[basePtr + i * 3 + 0] = moveMap[round.playerMove]
      memory[basePtr + i * 3 + 1] = moveMap[round.cpuMove]
      memory[basePtr + i * 3 + 2] = resultMap[round.result]
    }

    // Call WASM function
    const selectCPUMove = wasmInstance.exports.selectCPUMove as (
      roundsPtr: number,
      roundsLen: number,
      seed: number,
    ) => number
    const moveIndex = selectCPUMove(basePtr, rounds.length, seed % 0x7fffffff)

    return moveIndex >= 0 && moveIndex < 3 ? moveIndex : null
  } catch (err) {
    console.warn('WASM execution failed, falling back to JS:', err)
    return null
  }
}

/**
 * Determine round winner using WASM if available.
 * Returns: 0 = draw, 1 = player win, 2 = player loss
 */
export function getRoundWinnerWasm(playerMove: number, cpuMove: number): number | null {
  if (!wasmInstance) {
    return null
  }

  try {
    const getRoundWinner = wasmInstance.exports.getRoundWinner as (p: number, c: number) => number
    return getRoundWinner(playerMove, cpuMove)
  } catch (err) {
    console.warn('WASM getRoundWinner failed:', err)
    return null
  }
}

/**
 * Check if game is over using WASM if available.
 * Returns: 1 if game over, 0 if continues
 */
export function isGameOverWasm(
  playerScore: number,
  cpuScore: number,
  bestOf: number,
): boolean | null {
  if (!wasmInstance) {
    return null
  }

  try {
    const isGameOver = wasmInstance.exports.isGameOver as (
      p: number,
      c: number,
      b: number,
    ) => number
    return isGameOver(playerScore, cpuScore, bestOf) === 1
  } catch (err) {
    console.warn('WASM isGameOver failed:', err)
    return null
  }
}

/**
 * Determine game winner using WASM if available.
 * Returns: 0 = no winner, 1 = player wins, 2 = cpu wins
 */
export function determineGameWinnerWasm(
  playerScore: number,
  cpuScore: number,
  bestOf: number,
): 'player' | 'cpu' | null {
  if (!wasmInstance) {
    return null
  }

  try {
    const determineGameWinner = wasmInstance.exports.determineGameWinner as (
      p: number,
      c: number,
      b: number,
    ) => number
    const result = determineGameWinner(playerScore, cpuScore, bestOf)
    if (result === 1) {
      return 'player'
    }
    if (result === 2) {
      return 'cpu'
    }
    return null
  } catch (err) {
    console.warn('WASM determineGameWinner failed:', err)
    return null
  }
}
