// ═══════════════════════════════════════════════════════════════════════════
// WASM Build Pipeline
//
// 1. Compile AssemblyScript → .wasm binary
// 2. Encode .wasm to base64 → TypeScript module
//
// The base64-embedded approach eliminates fetch/URL issues across all
// platforms (browser, Electron file://, Capacitor WebView, blob Workers).
//
// Usage: pnpm wasm:build
// ═══════════════════════════════════════════════════════════════════════════

import { execSync } from 'child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

// ── 1. Ensure output directories ──────────────────────────────────────────
mkdirSync('build', { recursive: true })
mkdirSync('src/wasm', { recursive: true })

// ── 2. Compile AssemblyScript → WASM ──────────────────────────────────────
console.log('Compiling AssemblyScript → WASM...')

const isDebug = process.argv.includes('--debug')
const ascFlags = isDebug
  ? '--debug --runtime stub'
  : '--optimize --runtime stub --noAssert'

const asc = resolve('node_modules/.bin/asc')

execSync(
  `${asc} assembly/index.ts --outFile build/ai.wasm ${ascFlags}`,
  { stdio: 'inherit' },
)

// ── 3. Encode WASM binary → base64 TypeScript module ──────────────────────
const wasm = readFileSync('build/ai.wasm')
const base64 = wasm.toString('base64')
const sizeBytes = wasm.length
const sizeKB = (sizeBytes / 1024).toFixed(1)

const outputCode = [
  '// Auto-generated by scripts/build-wasm.js — do not edit manually',
  '// Rebuild with: pnpm wasm:build',
  `// Source: assembly/index.ts → build/ai.wasm (${sizeKB} KB, ${sizeBytes} bytes)`,
  '',
  `export const AI_WASM_BASE64 = '${base64}';`,
  '',
  `let wasmInstance: WebAssembly.Instance | null = null`,
  `let wasmMemory: WebAssembly.Memory | null = null`,
  `let dataBuffer: Int32Array | null = null`,
  '',
  `/**`,
  ` * Initialize WASM module if available.`,
  ` * This strategy falls back to JS if WASM fails.`,
  ` */`,
  `export async function initWasm(): Promise<boolean> {`,
  `  if (!AI_WASM_BASE64) {`,
  `    return false`,
  `  }`,
  '',
  `  try {`,
  `    const binaryString = atob(AI_WASM_BASE64)`,
  `    const bytes = new Uint8Array(binaryString.length)`,
  `    for (let i = 0; i < binaryString.length; i++) {`,
  `      bytes[i] = binaryString.charCodeAt(i)`,
  `    }`,
  '',
  `    const wasmModule = await WebAssembly.instantiate(bytes, {`,
  `      env: {`,
  `        __memory_base: 0,`,
  `      },`,
  `    })`,
  '',
  `    wasmInstance = wasmModule.instance`,
  `    wasmMemory = wasmModule.instance.exports.memory as WebAssembly.Memory`,
  `    dataBuffer = new Int32Array(wasmMemory.buffer)`,
  '',
  `    return true`,
  `  } catch (err) {`,
  `    console.warn('WASM initialization failed, falling back to JS:', err)`,
  `    return false`,
  `  }`,
  `}`,
  '',
  `/**`,
  ` * Select CPU move using WASM if available, otherwise fall back to JS.`,
  ` * Encodes rounds as flat Int32Array for WASM processing.`,
  ` */`,
  `export function selectCPUMoveWasm(`,
  `  rounds: Array<{ playerMove: string; cpuMove: string; result: string }>,`,
  `  seed: number,`,
  `): number | null {`,
  `  if (!wasmInstance || !dataBuffer) {`,
  `    return null`,
  `  }`,
  '',
  `  try {`,
  `    const memory = dataBuffer`,
  `    const basePtr = 0`,
  '',
  `    // Encode rounds into memory`,
  `    const moveMap: Record<string, number> = { rock: 0, paper: 1, scissors: 2 }`,
  `    const resultMap: Record<string, number> = { draw: 0, win: 1, loss: 2 }`,
  '',
  `    for (let i = 0; i < rounds.length; i++) {`,
  `      const round = rounds[i]`,
  `      memory[basePtr + i * 3 + 0] = moveMap[round.playerMove]`,
  `      memory[basePtr + i * 3 + 1] = moveMap[round.cpuMove]`,
  `      memory[basePtr + i * 3 + 2] = resultMap[round.result]`,
  `    }`,
  '',
  `    // Call WASM function`,
  `    const selectCPUMove = wasmInstance.exports.selectCPUMove as (`,
  `      roundsPtr: number,`,
  `      roundsLen: number,`,
  `      seed: number,`,
  `    ) => number`,
  `    const moveIndex = selectCPUMove(basePtr, rounds.length, seed % 0x7fffffff)`,
  '',
  `    return moveIndex >= 0 && moveIndex < 3 ? moveIndex : null`,
  `  } catch (err) {`,
  `    console.warn('WASM execution failed, falling back to JS:', err)`,
  `    return null`,
  `  }`,
  `}`,
].join('\n')

writeFileSync('src/wasm/ai-wasm.ts', outputCode)

console.log(
  `✓ WASM AI engine: ${sizeBytes} bytes (${sizeKB} KB) → src/wasm/ai-wasm.ts`,
)
